{% set name = "rack" %}
{% set version = "3.1.11" %}

package:
  name: rb-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://rubygems.org/downloads/{{ name }}-{{ version }}.gem
    sha256: 2b1111a754890d57e7bccefe3a8be28c0f9c02b43433b5a1276c07773e16e8f7

build:
  noarch: generic
  number: 0
  script:
    - gem install -N -l -V --norc --ignore-dependencies {{ name }}-{{ version }}.gem
    - gem unpack {{ name }}-{{ version }}.gem
    - cp {{ name }}-*/MIT-LICENSE .

requirements:
  host:
    - ruby >=2.7,<3
  run:
    - ruby >=2.7,<3

test:
  commands:
    - ruby -r {{ name }} -e 'exit 0'

about:
  home: https://rubygems.org/gems/{{ name }}
  license: MIT
  license_family: MIT
  license_file: MIT-LICENSE
  summary: A modular Ruby web server interface
  doc_url: https://www.rubydoc.info/gems/{{ name }}
  dev_url: https://github.com/rack/{{ name }}

extra:
  recipe-maintainers:
    - svengiegerich
    - janjagusch
